### ISSUE TITLE
njs2rpm fails if %_topdir is defined using macros

### ISSUE THREAD

**Issue by tomhughes** [sfreire/njs2rpm#1]
njs2rpm fails if `%_topdir` is defined using macros:

```
NJS2RPM v1.0.1 - NodeJs module to RPM converter by Sergio Freire <sergio-s-freire@ptinovacao.pt>
using RPM .spec template file /home/tom/src/njs2rpm/default.n2r ...
/home/tom/src/njs2rpm/njs2rpm: line 205: $SPECSDIR/$SPECFILE: ambiguous redirect
created %(echo
%{_topdir}/.gnupg/SPECS/nodejs-archiver.spec
```

In this case my `~/.rpmmacros` contains:

```
%_topdir %(echo "${HOME}/rpm")
```

The source appears to contain an alternate scheme using `rpm --eval` to get the root directory, which does work in this case.

**Comment by sfreire** [comment]
thanks @tomhughes. 
applying this fixes it. first obtaining the value from rpmmacros was extracting the value  not corretly; second, the value needs to be evaluated using rpm itself.

RPMTOPDIRVAL=$(cat ~/.rpmmacros 2> /dev/null| grep _topdir | cut -d " " -f 2- 2> /dev/null)
RPMTOPDIR=$(rpm --eval "$RPMTOPDIRVAL" 2> /dev/null)
